server:
  port: 9090  # Spring Boot Admin Server runs on port 9090

spring:
  application:
    name: admin-server
  boot:
    admin:
      client:
        url: http://localhost:8081  # Admin Server URL

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


