server:
  port: 8080

spring:
  application:
    name: api-gateway
  boot:
    admin:
      client:
        url: http://localhost:9090  # Corrected Admin Server URL

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery with Eureka
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
