eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
