server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hemanthsaich/config-repo.git  # Replace with your Git repository URL
          clone-on-start: true
          default-label: main
