server:
  port: 8081

spring:
  application:
    name: customer-service
  boot:
    admin:
      client:
        url: http://localhost:9090  # Corrected Admin Server URL

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    discovery:
      enabled: true

  sql:
    init:
      mode: always

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

h2:
  console:
    enabled: true
    path: /h2-console
